name: Deploy para Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Compress app
      run: zip -r app.zip .

    - name: Deploy para Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: webapp-sabor-caseiro
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./app.zip 